# ############################################################################################################# #
# +-----------------------------------------------------------------------------------------------------------+ #
# |                                                                                                           | #
# |     ██╗      █████╗ ██╗   ██╗ █████╗ ██████╗ ███████╗ █████╗  █████╗ ██╗   ██╗███████╗██████╗ ██╗   ██╗   | #
# |     ██║     ██╔══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██║   ██║██╔════╝██╔══██╗╚██╗ ██╔╝   | #
# |     ██║     ███████║╚██╗ ██╔╝███████║██████╔╝█████╗  ██║  ╚═╝██║  ██║╚██╗ ██╔╝█████╗  ██████╔╝ ╚████╔╝    | #
# |     ██║     ██╔══██║ ╚████╔╝ ██╔══██║██╔══██╗██╔══╝  ██║  ██╗██║  ██║ ╚████╔╝ ██╔══╝  ██╔══██╗  ╚██╔╝     | #
# |     ███████╗██║  ██║  ╚██╔╝  ██║  ██║██║  ██║███████╗╚█████╔╝╚█████╔╝  ╚██╔╝  ███████╗██║  ██║   ██║      | #
# |     ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ ╚════╝  ╚════╝    ╚═╝   ╚══════╝╚═╝  ╚═╝   ╚═╝      | #
# |                                                                                                           | #
# |                    Youtube:    www.youtube.com/@davigamer1614                                             | #
# |                    Github:     https://github.com/Guayand0/Minecraft-Plugin-LavaRecovery                  | #
# |                                                                                                           | #
# +-----------------------------------------------------------------------------------------------------------+ #
# ############################################################################################################# #

config:

  # You can add a new language adding (language.yml) to lang folder
  # If you want to have support for more languages by default, send
  # the .yml file with the translations and the language via GitHub
  # https://github.com/Guayand0/Minecraft-Plugin-LavaRecovery/issues

  # Available default languages: en, es
  # English - en.yml      Spanish - es.yml
  message-language: en

  # Enable/Disable the update checker
  update-checker: true

  # Chat prefix for plugin messages
  chat-prefix: "&4[&6&lLavaRecovery&4]&f"

  # Enable/Disable the lava recovery from obsidian
  lava-recovery: true

  # List of allowed worlds in which the plugin works
  allowed-worlds:
    - world
    - skyblock

  # Maximum number of recovery times allowed per player
  max-recovery-times-player: 5 # Set -1 to disable

  # Amount of time to recover lava from obsidian
  lava-recovery-cooldown: 60 # Time in seconds, Set -1 to disable
